A Dynamic Collection of Shell Scripts with Educational Purpose

diff --git a/scripts/fzffm b/scripts/fzffm
--- a/scripts/fzffm
+++ b/scripts/fzffm
@@ -56,6 +56,10 @@ else
     touch "$MARKED_FILES_FILE"
 fi
 
+# ANSI COLORS
+YELLOW="\033[1;33m"
+NC="\033[0m"
+
 clean_path() {
     local path="$1"
     echo "$path" | awk '{gsub(/^[[:space:]]+|[[:space:]]+$/, ""); gsub(/^'\''|'\''$/, ""); gsub(/'\''/, ""); gsub(/\\+/, ""); print}'
@@ -1431,14 +1435,17 @@ draw_file_preview() {
 
 ########################## FZF FILE MANAGER
 f_header_text() {
-	find_status=$([ -f "$CACHE_FZF_DIR/find" ] && echo "on" || echo "off")
-	cycle_status=$([ -f "$CACHE_FZF_DIR/cycle" ] && echo "on" || echo "off")
-	find_limited=$([ -f "$CACHE_FZF_DIR/find_limited" ] && echo "on" || echo "off")
-	preview_status=$([ ! -f "$CACHE_FZF_DIR/hidepreview" ] && echo "on" || echo "off")
+	grep_status=$([ -f "$TMP_FZF_DIR/grep" ] && echo -e "${YELLOW}on${NC}" || echo "off")
+	find_status=$([ -f "$CACHE_FZF_DIR/find" ] && echo -e "${YELLOW}on${NC}" || echo "off")
+	cycle_status=$([ -f "$CACHE_FZF_DIR/cycle" ] && echo -e "${YELLOW}on${NC}" || echo "off")
+	find_limited=$([ -f "$CACHE_FZF_DIR/find_limited" ] && echo -e "${YELLOW}on${NC}" || echo "off")
+	preview_status=$([ ! -f "$CACHE_FZF_DIR/hidepreview" ] && echo "on" || echo -e "${YELLOW}off${NC}")
 
 	# Builds header_text with marked Files
 	marked_files_status=""
-	if [ ${#marked_files[@]} -gt 0 ]; then
+	if [ ${#marked_files[@]} -gt 2 ]; then
+		marked_files_status="Marked files: ${#marked_files[@]}"
+	elif [ ${#marked_files[@]} -gt 0 ]; then
 		marked_files_status="Marked files:\n"
 		for file in "${marked_files[@]}"; do
 			if [[ -n "$file" ]]; then
@@ -1456,8 +1463,8 @@ f_header_text() {
 
 	cat <<-EOF | echo -e "$(cat)"
 	╭─ STATUS ────────────────────────╮
-	 ? for help |
-	 Limited Search:$find_limited
+	 ?/F1 for help | F5 reload
+	 Limited Search:$find_limited | Grep:$grep_status
 	 Preview:$preview_status | Cycle:$cycle_status | 🔍:$find_status
 	 $marked_files_status
 	╰─────────────────────────────────╯
@@ -1621,8 +1628,38 @@ safe_find_dirs() {
     fi
 }
 
+search_term() {
+    if ! command -v rg >/dev/null; then
+		messages "Error" "Error: Install ripgrep for search terms."
+		return 1
+    fi
+
+    # Asks the user the search term
+    search_term="$(whiptail --title "Grep Search" --inputbox "Enter search term: " 10 60 3>&1 1>&2 2>&3 >/dev/tty)"
+    
+    if [[ -z "$search_term" ]]; then
+        return
+    fi
+
+	rg --files-with-matches --color=never -i "$search_term" 2>/dev/null > "$TMP_FZF_DIR/grep" &
+	rg_pid=$!
+	printf '\e7\e[%sH\e[K%s\e8' "$(tput lines)" "Searching for matches. Please wait 5 seconds..." 
+
+	# Wait a maximum of 5s, but leaves before if the RG is over
+	for _ in {1..50}; do  
+		if ! kill -0 "$rg_pid" 2>/dev/null; then  
+			break  # Process already ended
+		fi  
+		sleep 0.1  # Checked every 0.1s (maximum total: 5s)
+	done  
+	clear  
+}
+
 safe_ls() {
-    if [[ -f "$CACHE_FZF_DIR/find" ]]; then
+	if [[ -f "$TMP_FZF_DIR/grep" ]]; then
+        print_filemanager_header "$1"
+		cat "$TMP_FZF_DIR/grep"
+    elif [[ -f "$CACHE_FZF_DIR/find" ]]; then
         print_filemanager_header "$1"
         { [[ -f "$CACHE_FZF_DIR/find_limited" ]] && safe_find_dirs_limited; } || safe_find_dirs
     else
@@ -2167,7 +2204,7 @@ extract_to_folder() {
         return 0
     }
 
-    printf '\e7\e[%sH\e[K%s\e8' 1000 "Extracting '$file' to '$folder_name'..." && sleep 1
+    printf '\e7\e[%sH\e[K%s\e8' "$(tput lines)" "Extracting '$file' to '$folder_name'..." && sleep 1
     
     case "$file_lower" in
         *.tar.bz2|*.tbz2)
@@ -2371,6 +2408,7 @@ fzf_binds() {
         --bind "alt-e:execute(bash \"$SCRIPT_PATH\" --extract-to-folder {})+top+accept"
         --bind "ctrl-z:execute(bash \"$SCRIPT_PATH\" --copy-to-clipboad {})+top+accept"
         --bind "ctrl-d,ctrl-e:execute(bash \"$SCRIPT_PATH\" --delete-file {})+top+accept"
+        --bind "ctrl-g:execute({ [ ! -f \"$TMP_FZF_DIR/grep\" ] && bash \"$SCRIPT_PATH\" --search-term; } || rm -f \"$TMP_FZF_DIR/grep\")+top+accept"
         --bind "ctrl-f:execute-silent({ [ ! -f \"$CACHE_FZF_DIR/find\" ] && touch \"$CACHE_FZF_DIR/find\"; } || rm -f \"$CACHE_FZF_DIR/find\")+top+accept"
         --bind "alt-a:toggle+execute-silent(bash \"$SCRIPT_PATH\" --mark-file {})+execute(bash \"$SCRIPT_PATH\" --update-header > \"$TMP_FZF_DIR/header\")"
         --bind "alt-c:execute-silent({ [ ! -f \"$CACHE_FZF_DIR/cycle\" ] && touch \"$CACHE_FZF_DIR/cycle\"; } || rm -f \"$CACHE_FZF_DIR/cycle\")+top+accept"
@@ -2455,6 +2493,9 @@ case "$1" in
     	;;
 	--create-directory)
 		create_directory
+		;;
+	--search-term)
+		search_term
 		;;
 	--create-file)
 		create_file
